### ISSUE TITLE
Image must be full perm to work when transferred

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/npose-ui#1]
[12:35] Aмαժєυѕ Yαкυвυ (Amadeus Alter): ok i have test i think script inside reading per uuid the pic for web. so must inside fullperm:-(. better idea i think read per NC with uuid. better protect work for buildner

**Comment by btubbs** [comment]
It's a good point, but there are tradeoffs.

1. Having the images in-prim means they can be read with llGetInventoryName, which you can do synchronously in a simple loop while building the http response.  Moving it to notecard lines would mean you'd have to read in all the lines on startup and hold them in memory.  This makes the script more complicated and use more sim resources.
2. It's a lot simpler for the creator to just drop a texture into a prim than to have to copy/paste UUIDs.

Someone could write a different implementation of my script that would work with notecard contents instead of textures in inventory.  As long as it had compatible http responses, it would even work with the existing ui.npose.org.  I probably won't be creating it though.

**Comment by nirea** [comment]
It's a good point, but there are tradeoffs.

1. Reading notecard lines takes a lot longer and is a lot more complicated for the script than reading inventory names.
2.  We'd have to hold the UUIDs in script memory..
3. It's more complicated for the creator to copy/paste UUIDs into a specially-formatted notecard than to drop in a texture and rename it.

If someone wants to make an alternate implementation that works with notecards, that's feasible.  It could even work with ui.npose.org, if it used the same http responses as my version.
